# Generated by Django 3.0.8 on 2020-07-08 00:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('restaurants', '0002_restaurant_user'),
    ]

    operations = [
        migrations.CreateModel(
            name='RestaurantType',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=80)),
            ],
            options={
                'verbose_name': 'Restaurant Type',
                'verbose_name_plural': 'Restaurant Types',
                'ordering': ('name', '-id'),
            },
        ),
        migrations.AlterModelOptions(
            name='restaurant',
            options={'ordering': ('name', '-id'), 'verbose_name': 'Restaurant', 'verbose_name_plural': 'Restaurants'},
        ),
        migrations.AddField(
            model_name='restaurant',
            name='closes',
            field=models.TimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='restaurant',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AddField(
            model_name='restaurant',
            name='delivery_price',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='restaurant',
            name='logo',
            field=models.ImageField(default='restaurants/noimage.png', upload_to='restaurants/'),
        ),
        migrations.AddField(
            model_name='restaurant',
            name='opens',
            field=models.TimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='restaurant',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='restaurant',
            name='name',
            field=models.CharField(max_length=128),
        ),
        migrations.AddField(
            model_name='restaurant',
            name='type',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='restaurants', to='restaurants.RestaurantType', verbose_name='Restaurant Type'),
        ),
    ]
