# Generated by Django 3.0.8 on 2020-07-15 02:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('foods', '0005_auto_20200715_0154'),
    ]

    operations = [
        migrations.AddField(
            model_name='food',
            name='cover',
            field=models.ImageField(blank=True, null=True, upload_to='foods/'),
        ),
    ]
