# Generated by Django 3.0.8 on 2020-07-15 02:32

import django.contrib.postgres.fields.jsonb
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('foods', '0006_food_cover'),
    ]

    operations = [
        migrations.AlterField(
            model_name='food',
            name='quantity',
            field=django.contrib.postgres.fields.jsonb.JSONField(blank=True, default=dict),
        ),
    ]
