# Generated by Django 3.0.8 on 2020-07-15 22:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orderproduct',
            name='comment',
            field=models.CharField(blank=True, max_length=300, null=True),
        ),
    ]
